#include "../header/Car.h"


//after each car class is created, input into a file, this will display all cars

//rent function should edit file and change car object from available to unavailable

//user ID should be generated by us for each car object created, so it is easier to remove and display

Car::Car(){
    carID = "00000";
    carMake = "none";
    carModel = "none";
    carColor = "none";
    carYear = 0;
    carNumberOfSeats = 0;
    carTransmission = "none";
    carHourlyRate = 0;
    renterID = "none";
    loanerID = "none";
    //becomes true once the car is booked by a user
    rented = false;
}

Car::Car(const string id, const string make, const string model, const string color, const int year, 
         const int seats, const string transmission, const double hourly_rate, string renter_id, const string loaner_id) {
    carID = id;
    carMake = make;
    carModel = model;
    carColor = color;
    carYear = year;
    carNumberOfSeats = seats;
    carTransmission = transmission;
    carHourlyRate = hourly_rate;
    renterID = renter_id;
    loanerID = loaner_id;
    //becomes true once the car is booked by a user
    rented = false;

}

//only job is to cout the car status
string Car::status() {
    if(rented){
        return "unavailable";
    }
    else{
        return "available";
    }
}

//HAS TO BE SEPERATE FROM STATUS
//has the ability to actually change the car renting status
void Car::rent() {
    if(!rented){
        rented = true;
    }
}

void Car::return_car(){
    if(rented){
        rented = false;
    }

}

void Car::display() {
    cout << "|| " << carID << " | " << carModel << " | " << carMake << " | " << carColor << " | " << carYear << " | " 
         << carNumberOfSeats << " | " << carTransmission << " | " << carHourlyRate << " | " << renterID << " | " << loanerID << " | " << status() << " ||";
    cout << endl;
}

//create operator function for <<

